name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  push-miniswag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    environment: release

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true
      - name: Push miniswag
        uses: rubygems/release-gem@v1

  push-miniswag-api:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    environment: release

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
      - name: Push miniswag-api
        uses: rubygems/release-gem@v1
        with:
          gem-directory: miniswag-api

  push-miniswag-ui:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    environment: release

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
      - name: Push miniswag-ui
        uses: rubygems/release-gem@v1
        with:
          gem-directory: miniswag-ui
